services:
  - type: web
    name: visa-form-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false
